### ISSUE TITLE
How to use pkl files of official stylegan?

### ISSUE THREAD

**Issue by wodsoe** [mchong6/SOAT#9]
How to use pkl files of official stylegan2 or stylegan3?

**Comment by mchong6** [comment]
you can only use stylegan2 files, and here's how you can convert the checkpoint https://github.com/rosinality/stylegan2-pytorch under Convert weight from official checkpoints

**Comment by wodsoe** [comment]
Thank you!

**Comment by wodsoe** [comment]
Could you update the code for stylegan3?
